-- Enable citext extension for case-insensitive text handling
CREATE EXTENSION IF NOT EXISTS citext;

-- ===========================================
-- Users Table
-- ===========================================
CREATE TABLE IF NOT EXISTS users (
    username CITEXT NOT NULL PRIMARY KEY,
    password CITEXT NOT NULL,
    enabled BOOLEAN NOT NULL
);

-- ===========================================
-- Authorities Table
-- ===========================================
CREATE TABLE IF NOT EXISTS authorities (
    username  CITEXT NOT NULL,
    authority CITEXT NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY(username) REFERENCES users(username)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_username
    ON authorities (username, authority);

-- ===========================================
-- Persistent Logins Table (Remember Me Feature)
-- ===========================================
CREATE TABLE IF NOT EXISTS persistent_logins (
    username  VARCHAR(64) NOT NULL,
    series    VARCHAR(64) PRIMARY KEY,
    token     VARCHAR(64) NOT NULL,
    last_used TIMESTAMP   NOT NULL
);

-- ===========================================
-- OAuth2 Authorized Client Table
-- ===========================================
CREATE TABLE IF NOT EXISTS oauth2_authorized_client (
    client_registration_id  VARCHAR(100)  NOT NULL,
    principal_name          VARCHAR(200)  NOT NULL,
    access_token_type       VARCHAR(100)  NOT NULL,
    access_token_value      BYTEA         NOT NULL,
    access_token_issued_at  TIMESTAMP     NOT NULL,
    access_token_expires_at TIMESTAMP     NOT NULL,
    access_token_scopes     VARCHAR(1000) DEFAULT NULL,
    refresh_token_value     BYTEA         DEFAULT NULL,
    refresh_token_issued_at TIMESTAMP     DEFAULT NULL,
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (client_registration_id, principal_name)
);

-- ===========================================
-- Audit Event Logs Table
-- ===========================================
CREATE TABLE IF NOT EXISTS audit_event_logs (
    id             BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(255)      NOT NULL,
    type           VARCHAR(255)      NOT NULL,
    code           INTEGER           NOT NULL,
    username       VARCHAR(255)      NOT NULL,
    authorities    VARCHAR(255),
    user_agent     VARCHAR(255),
    remote_address VARCHAR(255),
    session_id     VARCHAR(255),
    http_method    VARCHAR(255),
    request_uri    VARCHAR(255),
    request_body   VARCHAR(2097152),
    status         INTEGER,
    timestamp      TIMESTAMP(6)      NOT NULL
);

CREATE INDEX IF NOT EXISTS username_index
    ON audit_event_logs (username);

CREATE INDEX IF NOT EXISTS category_index
    ON audit_event_logs (category);

CREATE INDEX IF NOT EXISTS type_index
    ON audit_event_logs (type);

CREATE INDEX IF NOT EXISTS remote_address_index
    on audit_event_logs (remote_address);

CREATE INDEX IF NOT EXISTS timestamp_index
    ON audit_event_logs (timestamp);
